[tasks.clean]
dependencies = ["clean1", "clean2"]

[tasks.clean1]
command = "cargo"
args = ["clean"]

[tasks.clean2]
command = "rm"
args = ["-f", "image.jpg"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.runer]
script = ["cargo build --release && ./target/release/raytracing"]

[tasks.view]
command = "feh"
args = ["image.jpg"]

[tasks.run]
dependencies = ["runer", "view"]
