[tasks.clean]
dependencies = ["clean1", "clean2"]

[tasks.clean1]
command = "cargo"
args = ["clean"]

[tasks.clean2]
command = "rm"
args = ["-f", "image.ppm"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.runer]
script = ["cargo run > image.ppm"]

[tasks.view]
command = "feh"
args = ["image.ppm"]

[tasks.tests]
command = "cargo"
args = ["test"]

[tasks.test]
dependencies = ["build", "tests"]

[tasks.run]
dependencies = ["build", "runer", "view"]

[tasks.all]
dependencies = ["build", "tests", "runer", "view"]